### ISSUE TITLE
Problem after updating to 0.5.0

### ISSUE THREAD

**Issue by dblenkus** [tonioo/django-versionfield#3]
Hi,

`django-versionfield2` is causing an error in combination with [`django-autoslug`](https://github.com/neithere/django-autoslug/) after updating to version `0.5.0`.

It looks like `VersionField` is populated later than in previous versions and is still empty when `unique_with` constraint is checked in `AutoSlugField`.

I've prepared a [minimal example](https://github.com/dblenkus/versionfield-example) where you can test the behaviour. There are two requirements files. All requirements except `django-versionfield2` are the same and test passes with `requirements_working.txt` requirements and fails with `requirements_error.txt`.

Do you have any idea how to fix this?

Thanks,
Domen

**Comment by dblenkus** [comment]
@tonioo, have you had any time to look at the issue?

**Comment by tonioo** [comment]
@dblenkus I'm looking at your example but I don't encounter any error... How can I reproduce it ?

**Comment by dblenkus** [comment]
@tonioo thanks for your time!

Here are the exact steps to reproduce the error:

```
git clone https://github.com/dblenkus/versionfield-example
cd versionfield-example/
virtualenv error
source error/bin/activate
pip install -r requirements_error.txt
./manage.py test
```

And the output is:

```
Creating test database for alias 'default'...
E
======================================================================
ERROR: test_model (example.tests.ModelTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/domen/tmp/versionfield-example/example/tests.py", line 7, in test_model
    model = Model.objects.create(name="Test model")
  File "/Users/domen/tmp/versionfield-example/error/lib/python2.7/site-packages/django/db/models/manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/domen/tmp/versionfield-example/error/lib/python2.7/site-packages/django/db/models/query.py", line 401, in create
    obj.save(force_insert=True, using=self.db)
  File "/Users/domen/tmp/versionfield-example/error/lib/python2.7/site-packages/django/db/models/base.py", line 708, in save
    force_update=force_update, update_fields=update_fields)
  File "/Users/domen/tmp/versionfield-example/error/lib/python2.7/site-packages/django/db/models/base.py", line 736, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/Users/domen/tmp/versionfield-example/error/lib/python2.7/site-packages/django/db/models/base.py", line 820, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/Users/domen/tmp/versionfield-example/error/lib/python2.7/site-packages/django/db/models/base.py", line 859, in _do_insert
    using=using, raw=raw)
  File "/Users/domen/tmp/versionfield-example/error/lib/python2.7/site-packages/django/db/models/manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/domen/tmp/versionfield-example/error/lib/python2.7/site-packages/django/db/models/query.py", line 1039, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/Users/domen/tmp/versionfield-example/error/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 1059, in execute_sql
    for sql, params in self.as_sql():
  File "/Users/domen/tmp/versionfield-example/error/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 1019, in as_sql
    for obj in self.query.objs
  File "/Users/domen/tmp/versionfield-example/error/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 968, in pre_save_val
    return field.pre_save(obj, add=True)
  File "/Users/domen/tmp/versionfield-example/error/lib/python2.7/site-packages/autoslug/fields.py", line 279, in pre_save
    slug = utils.generate_unique_slug(self, instance, slug, manager)
  File "/Users/domen/tmp/versionfield-example/error/lib/python2.7/site-packages/autoslug/utils.py", line 57, in generate_unique_slug
    default_lookups = tuple(get_uniqueness_lookups(field, instance, field.unique_with))
  File "/Users/domen/tmp/versionfield-example/error/lib/python2.7/site-packages/autoslug/utils.py", line 130, in get_uniqueness_lookups
    field.name))
ValueError: Could not check uniqueness of Model.slug with respect to Model.version because the latter is empty. Please ensure that "slug" is declared *after* all fields listed in unique_with.

----------------------------------------------------------------------
Ran 1 test in 0.002s

FAILED (errors=1)
Destroying test database for alias 'default'...
```

But with old version of `django-versionfield` it works:

```
git clone https://github.com/dblenkus/versionfield-example
cd versionfield-example/
virtualenv working
source working/bin/activate
pip install -r requirements_working.txt
./manage.py test
```

And the output is:

```
/Users/domen/tmp/versionfield-example/working/lib/python2.7/site-packages/six.py:824: RemovedInDjango110Warning: SubfieldBase has been deprecated. Use Field.from_db_value instead.
  return metaclass(cls.__name__, cls.__bases__, orig_vars)

Creating test database for alias 'default'...
.
----------------------------------------------------------------------
Ran 1 test in 0.002s

OK
Destroying test database for alias 'default'...
```

**Comment by tonioo** [comment]
Ok. Just change your model definition like this and it will work :

``` python
class Model(models.Model):
    name = models.CharField(max_length=100)
    version = VersionField(default=0)
    slug = AutoSlugField(populate_from='name')

    class Meta:
        unique_together = ("slug", "version")
```
